import type { FixtureTypeCatalogEntry } from "../types.ts";

/**
 * Fixture Type catalog — planned competitive structure kinds (EPIC-06).
 * Swiss / Double Elimination are catalog stubs (no generators this epic).
 */
export const FIXTURE_TYPE_CATALOG: readonly FixtureTypeCatalogEntry[] = [
  {
    kind: "fixture_type",
    id: "league",
    version: "1.0.0",
    displayName: "League",
    description: "League-style planned structure.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "recommended",
  },
  {
    kind: "fixture_type",
    id: "knockout",
    version: "1.0.0",
    displayName: "Knockout",
    description: "Single-elimination planned structure.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "recommended",
  },
  {
    kind: "fixture_type",
    id: "round_robin",
    version: "1.0.0",
    displayName: "Round Robin",
    description: "Round-robin planned structure.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "recommended",
  },
  {
    kind: "fixture_type",
    id: "group",
    version: "1.0.0",
    displayName: "Group",
    description: "Group-stage planned structure.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "recommended",
  },
  {
    kind: "fixture_type",
    id: "swiss",
    version: "1.0.0",
    displayName: "Swiss",
    description: "Swiss-system structure (generator deferred).",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "beta",
    recommendation: "advanced",
  },
  {
    kind: "fixture_type",
    id: "double_elimination",
    version: "1.0.0",
    displayName: "Double Elimination",
    description: "Double-elimination structure (generator deferred).",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "beta",
    recommendation: "advanced",
  },
  {
    kind: "fixture_type",
    id: "custom",
    version: "1.0.0",
    displayName: "Custom",
    description: "Organizer-defined planned structure.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "advanced",
  },
];
