/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuctionRouteImport } from './routes/auction'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuctionIndexRouteImport } from './routes/auction.index'
import { Route as AuctionV1RouteImport } from './routes/auction.v1'

const AuctionRoute = AuctionRouteImport.update({
  id: '/auction',
  path: '/auction',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionIndexRoute = AuctionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuctionRoute,
} as any)
const AuctionV1Route = AuctionV1RouteImport.update({
  id: '/v1',
  path: '/v1',
  getParentRoute: () => AuctionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auction': typeof AuctionRouteWithChildren
  '/auction/v1': typeof AuctionV1Route
  '/auction/': typeof AuctionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auction/v1': typeof AuctionV1Route
  '/auction': typeof AuctionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auction': typeof AuctionRouteWithChildren
  '/auction/v1': typeof AuctionV1Route
  '/auction/': typeof AuctionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auction' | '/auction/v1' | '/auction/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auction/v1' | '/auction'
  id: '__root__' | '/' | '/auction' | '/auction/v1' | '/auction/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionRoute: typeof AuctionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auction': {
      id: '/auction'
      path: '/auction'
      fullPath: '/auction'
      preLoaderRoute: typeof AuctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/': {
      id: '/auction/'
      path: '/'
      fullPath: '/auction/'
      preLoaderRoute: typeof AuctionIndexRouteImport
      parentRoute: typeof AuctionRoute
    }
    '/auction/v1': {
      id: '/auction/v1'
      path: '/v1'
      fullPath: '/auction/v1'
      preLoaderRoute: typeof AuctionV1RouteImport
      parentRoute: typeof AuctionRoute
    }
  }
}

interface AuctionRouteChildren {
  AuctionV1Route: typeof AuctionV1Route
  AuctionIndexRoute: typeof AuctionIndexRoute
}

const AuctionRouteChildren: AuctionRouteChildren = {
  AuctionV1Route: AuctionV1Route,
  AuctionIndexRoute: AuctionIndexRoute,
}

const AuctionRouteWithChildren =
  AuctionRoute._addFileChildren(AuctionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionRoute: AuctionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
