export const PLAYER_IMAGE_PLACEHOLDER = "PLAYER_IMAGE_PLACEHOLDER";

export const TEAM_LOGO_PLACEHOLDER = "TEAM_LOGO_PLACEHOLDER";

export const TOURNAMENT_BANNER_PLACEHOLDER = "TOURNAMENT_BANNER_PLACEHOLDER";

export const QR_PLACEHOLDER = "QR_PLACEHOLDER";
