import type { AdvancementRuleCatalogEntry } from "../types.ts";

/**
 * Advancement Rule catalog — progression policies (EPIC-06).
 * Generators consume these; they must not embed winner/loser/group logic as platform truth.
 */
export const ADVANCEMENT_RULE_CATALOG: readonly AdvancementRuleCatalogEntry[] = [
  {
    kind: "advancement_rule",
    id: "winner_advances",
    version: "1.0.0",
    displayName: "Winner Advances",
    description: "Winner of a contest advances to a target node.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "recommended",
  },
  {
    kind: "advancement_rule",
    id: "loser_advances",
    version: "1.0.0",
    displayName: "Loser Advances",
    description: "Loser of a contest advances to a target node (consolation / DE).",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "recommended",
  },
  {
    kind: "advancement_rule",
    id: "points_table",
    version: "1.0.0",
    displayName: "Points Table",
    description: "Advancement derived from a points table.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "recommended",
  },
  {
    kind: "advancement_rule",
    id: "group_qualification",
    version: "1.0.0",
    displayName: "Group Qualification",
    description: "Qualification from group standings into later stages.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "recommended",
  },
  {
    kind: "advancement_rule",
    id: "best_performer",
    version: "1.0.0",
    displayName: "Best Performer",
    description: "Best performer / best runner-up style qualification.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "advanced",
  },
  {
    kind: "advancement_rule",
    id: "manual",
    version: "1.0.0",
    displayName: "Manual",
    description: "Organizer-assigned advancement.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "advanced",
  },
  {
    kind: "advancement_rule",
    id: "future",
    version: "1.0.0",
    displayName: "Future",
    description: "Reserved for future advancement policies.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "beta",
    recommendation: "advanced",
  },
];
