import type { CompetitionTypeCatalogEntry } from "../types.ts";

export const COMPETITION_TYPE_CATALOG: readonly CompetitionTypeCatalogEntry[] = [
  {
    kind: "competition",
    id: "auction",
    version: "1.0.0",
    displayName: "Auction",
    description: "Franchise teams acquire players through a live auction.",
    supportedCompetitionTypes: ["auction"],
    supportedVariants: ["*"],
    status: "default",
    recommendation: "recommended",
    requiresAuctionEconomics: true,
  },
  {
    kind: "competition",
    id: "registered_teams",
    version: "1.0.0",
    displayName: "Registered Teams",
    description: "Teams register complete squads — no auction required.",
    supportedCompetitionTypes: ["registered_teams"],
    supportedVariants: ["*"],
    status: "default",
    recommendation: "recommended",
    requiresAuctionEconomics: false,
  },
  {
    kind: "competition",
    id: "hybrid",
    version: "1.0.0",
    displayName: "Hybrid",
    description: "Mix of registered players and auction picks.",
    supportedCompetitionTypes: ["hybrid"],
    supportedVariants: ["*"],
    status: "default",
    recommendation: "advanced",
    requiresAuctionEconomics: true,
  },
  {
    kind: "competition",
    id: "practice",
    version: "1.0.0",
    displayName: "Practice",
    description: "Practice or friendly competition without formal standings pressure.",
    supportedCompetitionTypes: ["practice"],
    supportedVariants: ["*"],
    status: "default",
    recommendation: "auto_suggested",
    requiresAuctionEconomics: false,
  },
];
