import { def } from "./helpers.ts";

export const BADMINTON_RULE_DEFINITIONS = [
  def({
    id: "badminton.match.total_games",
    name: "Total games",
    description: "Best-of games in the match (odd).",
    categoryId: "match",
    sportId: "badminton",
    type: "integer",
    defaultValue: 3,
    allowedValues: [1, 3, 5],
    validation: { required: true },
  }),
  def({
    id: "badminton.match.points_per_game",
    name: "Points per game",
    description: "Points required to win a game before deuce rules.",
    categoryId: "match",
    sportId: "badminton",
    type: "integer",
    defaultValue: 21,
    validation: { required: true, min: 1, max: 30 },
  }),
  def({
    id: "badminton.match.deuce_at",
    name: "Deuce at",
    description: "Score threshold that enters deuce / win-by territory.",
    categoryId: "match",
    sportId: "badminton",
    type: "integer",
    defaultValue: 20,
    validation: { required: true, min: 1, max: 30 },
  }),
  def({
    id: "badminton.match.max_points",
    name: "Max points",
    description: "Hard cap on points in a game.",
    categoryId: "match",
    sportId: "badminton",
    type: "integer",
    defaultValue: 30,
    validation: { required: true, min: 1, max: 50 },
  }),
  def({
    id: "badminton.match.mid_game_side_change",
    name: "Mid-game side change",
    description: "Whether sides change ends mid deciding game.",
    categoryId: "match",
    sportId: "badminton",
    type: "boolean",
    defaultValue: true,
  }),
  def({
    id: "badminton.tournament.preset_id",
    name: "Match format preset",
    description: "Runtime badminton match-format preset id (product reference).",
    categoryId: "tournament",
    sportId: "badminton",
    type: "enum",
    defaultValue: "standard_bwf",
    allowedValues: ["standard_bwf", "fast_match", "single_game", "custom"],
    validation: { required: true },
  }),
] as const;
