import { def } from "./helpers.ts";

export const CRICKET_RULE_DEFINITIONS = [
  def({
    id: "cricket.match.overs_per_innings",
    name: "Overs per innings",
    description: "Scheduled overs limit for each innings.",
    categoryId: "match",
    sportId: "cricket",
    type: "integer",
    defaultValue: 20,
    validation: { required: true, min: 1, max: 50 },
  }),
  def({
    id: "cricket.match.max_wickets",
    name: "Max wickets",
    description: "All-out threshold (wickets).",
    categoryId: "match",
    sportId: "cricket",
    type: "integer",
    defaultValue: 10,
    validation: { required: true, min: 1, max: 15 },
  }),
  def({
    id: "cricket.match.playing_squad_size",
    name: "Playing squad size",
    description: "Number of players allowed in the playing XI.",
    categoryId: "match",
    sportId: "cricket",
    type: "integer",
    defaultValue: 11,
    validation: { required: true, min: 1, max: 15 },
  }),
  def({
    id: "cricket.match.playing_xi_enforced",
    name: "Enforce exact Playing XI",
    description:
      "Whether the configured playing squad size is an exact required count.",
    categoryId: "match",
    sportId: "cricket",
    type: "boolean",
    defaultValue: false,
  }),
  def({
    id: "cricket.match.bench_size",
    name: "Bench size",
    description: "Typical bench slots accompanying the playing squad.",
    categoryId: "match",
    sportId: "cricket",
    type: "integer",
    defaultValue: 4,
    validation: { min: 0, max: 10 },
  }),
  def({
    id: "cricket.match.balls_per_over",
    name: "Balls per over",
    description: "Legal balls required to complete an over.",
    categoryId: "match",
    sportId: "cricket",
    type: "integer",
    defaultValue: 6,
    validation: { required: true, min: 1, max: 8 },
  }),
  def({
    id: "cricket.match.ball_type",
    name: "Ball type",
    description: "Informational ball type metadata.",
    categoryId: "match",
    sportId: "cricket",
    type: "enum",
    defaultValue: "leather",
    allowedValues: ["leather", "tennis", "tape", "indoor"],
  }),
  def({
    id: "cricket.dismissal.lbw_enabled",
    name: "LBW enabled",
    description: "Whether LBW dismissals are legal under this profile.",
    categoryId: "dismissal",
    sportId: "cricket",
    type: "boolean",
    defaultValue: true,
  }),
  def({
    id: "cricket.extras.leg_bye_enabled",
    name: "Leg bye enabled",
    description: "Whether leg-bye extras are legal under this profile.",
    categoryId: "extras",
    sportId: "cricket",
    type: "boolean",
    defaultValue: true,
  }),
  def({
    id: "cricket.special.super_ball_enabled",
    name: "Super Ball enabled",
    description:
      "Whether the match supports one pre-declared Super Ball per innings.",
    categoryId: "special",
    sportId: "cricket",
    type: "boolean",
    defaultValue: false,
  }),
  def({
    id: "cricket.bowling.free_hit_enabled",
    name: "Free hit enabled",
    description: "Whether free-hit deliveries are awarded after no-balls.",
    categoryId: "bowling",
    sportId: "cricket",
    type: "boolean",
    defaultValue: true,
  }),
  def({
    id: "cricket.batting.retire_at_runs",
    name: "Retire at runs",
    description: "Optional auto-retire threshold; null means disabled.",
    categoryId: "batting",
    sportId: "cricket",
    type: "integer",
    defaultValue: null,
    validation: { min: 1, max: 500 },
  }),
  def({
    id: "cricket.powerplay.enabled",
    name: "Powerplay enabled",
    description: "Whether powerplay phases are part of match policy.",
    categoryId: "powerplay",
    sportId: "cricket",
    type: "boolean",
    defaultValue: true,
  }),
  def({
    id: "cricket.tie_break.super_over_enabled",
    name: "Super over enabled",
    description: "Whether super over is used to break ties.",
    categoryId: "tie_break",
    sportId: "cricket",
    type: "boolean",
    defaultValue: true,
    dependencies: ["cricket.tie_break.ties_allowed"],
  }),
  def({
    id: "cricket.tie_break.super_over_overs",
    name: "Super over overs",
    description: "Overs available to each team in a Super Over tie-break.",
    categoryId: "tie_break",
    sportId: "cricket",
    type: "integer",
    defaultValue: 1,
    validation: { min: 1, max: 5 },
  }),
  def({
    id: "cricket.tie_break.super_over_wickets",
    name: "Super over wickets",
    description:
      "Wickets available to the batting team in a Super Over tie-break.",
    categoryId: "tie_break",
    sportId: "cricket",
    type: "integer",
    defaultValue: 2,
    validation: { min: 1, max: 10 },
  }),
  def({
    id: "cricket.tie_break.super_over_trigger",
    name: "Super over trigger",
    description: "When Super Over may be started for this match.",
    categoryId: "tie_break",
    sportId: "cricket",
    type: "enum",
    defaultValue: "manual",
    allowedValues: ["manual", "knockout_tie"],
  }),
  def({
    id: "cricket.tie_break.ties_allowed",
    name: "Ties allowed",
    description:
      "Whether a match may end as a tie before tie-break procedures.",
    categoryId: "tie_break",
    sportId: "cricket",
    type: "boolean",
    defaultValue: true,
  }),
  def({
    id: "cricket.boundary.four_runs",
    name: "Four runs",
    description: "Runs awarded for a boundary four.",
    categoryId: "boundary",
    sportId: "cricket",
    type: "integer",
    defaultValue: 4,
    validation: { min: 1, max: 8 },
  }),
  def({
    id: "cricket.boundary.six_runs",
    name: "Six runs",
    description: "Runs awarded for a boundary six.",
    categoryId: "boundary",
    sportId: "cricket",
    type: "integer",
    defaultValue: 6,
    validation: { min: 1, max: 12 },
  }),
] as const;
