/**
 * Buzz Studio — Template Previews
 *
 * Placeholder preview metadata for every template.
 * Currently metadata-only — no image assets.
 *
 * Future: previewImage will hold a static PNG path (e.g. "/buzz-studio/previews/player-spotlight.png")
 * generated by the PNG renderer during a build step.
 *
 * The registry merges these previews into each BuzzTemplateRegistryEntry so
 * the dashboard has a single object to work with per template.
 */

import { BuzzTemplateType } from "./template-types";
import type { BuzzTemplatePreview } from "./registry-types";

/* ─────────────────────────────────────────────────────────────────────────── */
/*  Preview map                                                                */
/* ─────────────────────────────────────────────────────────────────────────── */

export const TEMPLATE_PREVIEWS: Readonly<Record<BuzzTemplateType, BuzzTemplatePreview>> = {
  [BuzzTemplateType.PLAYER_SPOTLIGHT]: {
    templateId: BuzzTemplateType.PLAYER_SPOTLIGHT,
    previewTitle: "Player Spotlight",
  },

  [BuzzTemplateType.SOLD_PLAYER]: {
    templateId: BuzzTemplateType.SOLD_PLAYER,
    previewTitle: "Sold Player",
  },

  [BuzzTemplateType.TOP_BUYS]: {
    templateId: BuzzTemplateType.TOP_BUYS,
    previewTitle: "Top Buys",
  },

  [BuzzTemplateType.TEAM_REVEAL]: {
    templateId: BuzzTemplateType.TEAM_REVEAL,
    previewTitle: "Team Reveal",
  },

  [BuzzTemplateType.TEAM_SQUAD]: {
    templateId: BuzzTemplateType.TEAM_SQUAD,
    previewTitle: "Team Squad",
  },

  [BuzzTemplateType.AUCTION_SUMMARY]: {
    templateId: BuzzTemplateType.AUCTION_SUMMARY,
    previewTitle: "Auction Summary",
  },

  [BuzzTemplateType.MVP_CARD]: {
    templateId: BuzzTemplateType.MVP_CARD,
    previewTitle: "MVP Card",
  },

  [BuzzTemplateType.TOURNAMENT_LAUNCH]: {
    templateId: BuzzTemplateType.TOURNAMENT_LAUNCH,
    previewTitle: "Tournament Launch",
  },
} as const;
