import { Router, type IRouter } from "express";
import healthRouter from "./health";
import uploadRouter from "./upload";
import tournamentsRouter from "./tournaments";
import teamsRouter from "./teams";
import categoriesRouter from "./categories";
import playersRouter from "./players";
import auctionRouter from "./auction";
import analyticsRouter from "./analytics";
import authRouter from "./auth";
import adminReportsRouter from "./admin-reports";
import intelligenceRouter from "./intelligence";
import seedDemoRouter from "./seed-demo";
import globalPlayersRouter from "./global-players";
import commRouter from "./comm";
import webhooksRouter from "./webhooks";
import sportsRouter from "./sports";
import brandingRouter from "./branding";
import pushRouter from "./push";
import settingsRouter from "./settings";
import displayAuctionsRouter from "./display-auctions";
import showcaseRouter from "./showcase";
import teamReportsRouter from "./team-reports";
import ownerOnboardingRouter from "./owner-onboarding";
import notificationsRouter from "./notifications";
import auditRouter from "./audit";
import purseBoostersRouter from "./purse-boosters";
import scoringRouter from "./scoring";
import badmintonRouter from "./badminton";
import masterSportsRouter from "./master-sports";
import cricketMasterSportsRouter from "./cricket-master-sports";
import scoringFoundationRouter from "./scoring-foundation";
import creativeJobsRouter from "./creative-jobs";
import contactRouter from "./contact";
import communicationCenterRouter from "./communication-center";
import googleSheetsRouter from "./google-sheets";

const router: IRouter = Router();

router.use(authRouter);
router.use(googleSheetsRouter);
router.use(pushRouter);
router.use(healthRouter);
router.use(uploadRouter);
router.use(brandingRouter);
router.use(tournamentsRouter);
router.use(teamsRouter);
router.use(categoriesRouter);
router.use(playersRouter);
router.use(auctionRouter);
router.use(analyticsRouter);
router.use(adminReportsRouter);
router.use(intelligenceRouter);
router.use(seedDemoRouter);
router.use(globalPlayersRouter);
router.use(commRouter);
router.use(webhooksRouter);
router.use(sportsRouter);
router.use(settingsRouter);
router.use(displayAuctionsRouter);
router.use(showcaseRouter);
router.use(teamReportsRouter);
router.use(ownerOnboardingRouter);
router.use(notificationsRouter);
router.use(auditRouter);
router.use(purseBoostersRouter);
router.use(creativeJobsRouter);
router.use(scoringRouter);
router.use(contactRouter);
router.use(communicationCenterRouter);
router.use("/tournaments/:id/badminton", badmintonRouter);
router.use("/tournaments/:id/badminton", masterSportsRouter);
router.use("/tournaments/:id/scoring", cricketMasterSportsRouter);
router.use("/tournaments/:tournamentId/scoring", scoringFoundationRouter);

export default router;
