import { Router, type IRouter } from "express";
import healthRouter from "./health";
import uploadRouter from "./upload";
import tournamentsRouter from "./tournaments";
import teamsRouter from "./teams";
import categoriesRouter from "./categories";
import playersRouter from "./players";
import auctionRouter from "./auction";
import analyticsRouter from "./analytics";
import authRouter from "./auth";
import adminReportsRouter from "./admin-reports";
import intelligenceRouter from "./intelligence";
import seedDemoRouter from "./seed-demo";
import globalPlayersRouter from "./global-players";
import commRouter from "./comm";
import webhooksRouter from "./webhooks";
import sportsRouter from "./sports";
import brandingRouter from "./branding";
import pushRouter from "./push";
import settingsRouter from "./settings";

const router: IRouter = Router();

router.use(authRouter);
router.use(pushRouter);
router.use(healthRouter);
router.use(uploadRouter);
router.use(brandingRouter);
router.use(tournamentsRouter);
router.use(teamsRouter);
router.use(categoriesRouter);
router.use(playersRouter);
router.use(auctionRouter);
router.use(analyticsRouter);
router.use(adminReportsRouter);
router.use(intelligenceRouter);
router.use(seedDemoRouter);
router.use(globalPlayersRouter);
router.use(commRouter);
router.use(webhooksRouter);
router.use(sportsRouter);
router.use(settingsRouter);

export default router;
