import type { TeamRoleCatalogEntry } from "../types.ts";

/**
 * Team Role catalog — membership roles (EPIC-04).
 * Constraints live here; validators read the catalog (never hardcode role rules).
 */
export const TEAM_ROLE_CATALOG: readonly TeamRoleCatalogEntry[] = [
  {
    kind: "team_role",
    id: "captain",
    version: "1.0.0",
    displayName: "Captain",
    description: "Team captain. Exactly one required.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    required: true,
    multipleAllowed: false,
    maxCount: 1,
  },
  {
    kind: "team_role",
    id: "vice_captain",
    version: "1.0.0",
    displayName: "Vice Captain",
    description: "Deputy captain. At most one.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    required: false,
    multipleAllowed: false,
    maxCount: 1,
  },
  {
    kind: "team_role",
    id: "player",
    version: "1.0.0",
    displayName: "Player",
    description: "Playing member.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    required: false,
    multipleAllowed: true,
    maxCount: null,
  },
  {
    kind: "team_role",
    id: "coach",
    version: "1.0.0",
    displayName: "Coach",
    description: "Coaching staff. Optional, multiple allowed.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    required: false,
    multipleAllowed: true,
    maxCount: null,
  },
  {
    kind: "team_role",
    id: "manager",
    version: "1.0.0",
    displayName: "Manager",
    description: "Team manager. Optional, multiple allowed.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    required: false,
    multipleAllowed: true,
    maxCount: null,
  },
  {
    kind: "team_role",
    id: "owner",
    version: "1.0.0",
    displayName: "Owner",
    description: "Team owner / franchise holder. Optional, multiple allowed.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    required: false,
    multipleAllowed: true,
    maxCount: null,
  },
  {
    kind: "team_role",
    id: "support_staff",
    version: "1.0.0",
    displayName: "Support Staff",
    description: "Non-playing support (physio, analyst, etc.).",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    required: false,
    multipleAllowed: true,
    maxCount: null,
  },
  {
    kind: "team_role",
    id: "official",
    version: "1.0.0",
    displayName: "Official",
    description: "Team-affiliated official.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    required: false,
    multipleAllowed: true,
    maxCount: null,
  },
];
