"use strict";

const express = require("express");
const expressStaticGzip = require("express-static-gzip");
const path = require("path");

const PORT = parseInt(process.env.PORT || "3000", 10);
const DIST = path.join(__dirname, "dist", "public");

const app = express();

// Serve pre-compressed static files.
// express-static-gzip negotiates Accept-Encoding and serves .br or .gz
// sidecar files generated by vite-plugin-compression2 at build time.
app.use(
  "/",
  expressStaticGzip(DIST, {
    enableBrotli: true,
    orderPreference: ["br", "gz"],
    serveStatic: {
      // Cache-control: hashed assets are immutable forever; index.html never.
      setHeaders(res, filePath) {
        const base = path.basename(filePath).replace(/\.(br|gz)$/, "");
        if (base === "index.html" || base === "site.webmanifest") {
          res.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
        } else {
          res.setHeader(
            "Cache-Control",
            "public, max-age=31536000, immutable",
          );
        }
      },
    },
  }),
);

// SPA fallback: unknown paths → index.html so client-side routing works.
// app.use (not app.get) avoids the Express 5 named-wildcard requirement.
app.use((_req, res) => {
  res.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  res.sendFile(path.join(DIST, "index.html"));
});

app.listen(PORT, "0.0.0.0", () => {
  process.stdout.write(`BidWar frontend serving on port ${PORT}\n`);
});
