import type { SchedulingStrategyCatalogEntry } from "../types.ts";

/**
 * Scheduling Strategy catalog (EPIC-07).
 * Schedulers (bridges) consume these; strategies never contain algorithms.
 */
export const SCHEDULING_STRATEGY_CATALOG: readonly SchedulingStrategyCatalogEntry[] = [
  {
    kind: "scheduling_strategy",
    id: "manual",
    version: "1.0.0",
    displayName: "Manual",
    description: "Organizer assigns slots and resources manually.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "recommended",
  },
  {
    kind: "scheduling_strategy",
    id: "sequential",
    version: "1.0.0",
    displayName: "Sequential",
    description: "Sequential slot placement policy.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "recommended",
  },
  {
    kind: "scheduling_strategy",
    id: "parallel",
    version: "1.0.0",
    displayName: "Parallel",
    description: "Allow parallel matches across resources.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "recommended",
  },
  {
    kind: "scheduling_strategy",
    id: "round_robin_optimized",
    version: "1.0.0",
    displayName: "Round Robin Optimized",
    description: "Policy label for RR-oriented scheduling (algorithm behind bridge).",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "advanced",
  },
  {
    kind: "scheduling_strategy",
    id: "knockout_optimized",
    version: "1.0.0",
    displayName: "Knockout Optimized",
    description: "Policy label for knockout-oriented scheduling (algorithm behind bridge).",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "advanced",
  },
  {
    kind: "scheduling_strategy",
    id: "balanced",
    version: "1.0.0",
    displayName: "Balanced",
    description: "Balanced load across resources.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "advanced",
  },
  {
    kind: "scheduling_strategy",
    id: "future",
    version: "1.0.0",
    displayName: "Future",
    description: "Reserved for future strategies.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "beta",
    recommendation: "advanced",
  },
];
