const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');

class Range { constructor(sheet, row, col, rows, cols) { Object.assign(this, { sheet, row, col, rows, cols }); } getValues() { return Array.from({ length: this.rows }, (_, r) => Array.from({ length: this.cols }, (_, c) => this.sheet.cells[this.row - 1 + r]?.[this.col - 1 + c] ?? '')); } setValues(values) { values.forEach((line, r) => line.forEach((value, c) => { (this.sheet.cells[this.row - 1 + r] ||= [])[this.col - 1 + c] = value; })); } }
class Sheet { constructor(name) { this.name = name; this.cells = []; this.frozen = 0; } getSheetName() { return this.name; } getLastRow() { return this.cells.reduce((last, row, index) => row?.some(v => v !== '') ? index + 1 : last, 0); } getLastColumn() { return this.cells.reduce((max, row) => Math.max(max, row?.length || 0), 0); } getRange(...args) { return new Range(this, ...args); } setFrozenRows(rows) { this.frozen = rows; } }
class Spreadsheet { constructor(id) { this.id = id; this.sheets = [new Sheet('Sheet1')]; } getId() { return this.id; } getUrl() { return `https://docs.google.com/spreadsheets/d/${this.id}`; } getSheets() { return this.sheets; } getSheetByName(name) { return this.sheets.find(sheet => sheet.name === name) || null; } insertSheet(name) { const sheet = new Sheet(name); this.sheets.push(sheet); return sheet; } deleteSheet(sheet) { this.sheets = this.sheets.filter(item => item !== sheet); } }
const props = {}; const books = new Map(); let created = 0;
const context = { console, Date, JSON, Object, String, Number, Array, Set, Math, PropertiesService: { getScriptProperties: () => ({ getProperty: key => props[key] ?? null, setProperties: values => Object.assign(props, values), deleteProperty: key => delete props[key] }) }, LockService: { getScriptLock: () => ({ waitLock() {}, releaseLock() {} }) }, SpreadsheetApp: { create: () => { const book = new Spreadsheet(`sheet-${++created}`); books.set(book.getId(), book); return book; }, openById: id => books.get(id) }, CacheService: { getScriptCache: () => ({ get: () => null, put: () => {} }) }, ContentService: { createTextOutput: value => ({ value, setMimeType() { return this; } }), MimeType: { JSON: 'JSON' } }, MailApp: { sendEmail() {} } };
vm.createContext(context); vm.runInContext(fs.readFileSync(`${__dirname}/Code.gs`, 'utf8'), context);
const first = vm.runInContext('setupBplRegistration()', context); assert.equal(created, 1); assert.equal(props.SPREADSHEET_ID, 'sheet-1'); assert.equal(props.BPL_OWNED_SPREADSHEET_ID, 'sheet-1'); assert.match(first.spreadsheetUrl, /sheet-1$/);
const schema = vm.runInContext('SCHEMA', context); const book = books.get('sheet-1'); assert.equal(JSON.stringify(book.getSheets().map(sheet => sheet.getSheetName()).sort()), JSON.stringify(Object.keys(schema).sort())); Object.entries(schema).forEach(([name, headers]) => assert.equal(JSON.stringify(book.getSheetByName(name).getRange(1, 1, 1, headers.length).getValues()[0]), JSON.stringify(headers)));
const registrations = book.getSheetByName('REGISTRATIONS'); registrations.getRange(2, 1, 1, 1).setValues([['existing registration']]); vm.runInContext('setupBplRegistration()', context); assert.equal(created, 1); assert.equal(registrations.getRange(2, 1, 1, 1).getValues()[0][0], 'existing registration');
console.log('Apps Script setup tests passed: creates one owned sheet, seven schema tabs/headers (including SETTINGS), persists ID, and preserves data on repeat setup.');
const settingsSheet = book.getSheetByName('SETTINGS'); const settingRows = settingsSheet.getRange(2, 1, settingsSheet.getLastRow() - 1, 2).getValues(); const values = Object.fromEntries(settingRows); assert.equal(values.REGISTRATION_ENABLED, 'false'); assert.ok(values.REGISTRATION_END);
const findSettingRow = key => settingRows.findIndex(([name]) => name === key) + 2; settingsSheet.getRange(findSettingRow('REGISTRATION_END'), 2, 1, 1).setValues([['2000-01-01T00:00:00+05:30']]); assert.equal(vm.runInContext('isOpen_(config_())', context), false);
settingsSheet.getRange(findSettingRow('REGISTRATION_ENABLED'), 2, 1, 1).setValues([['TRUE']]); settingsSheet.getRange(findSettingRow('REGISTRATION_START'), 2, 1, 1).setValues([['2000-01-01T00:00:00+05:30']]); settingsSheet.getRange(findSettingRow('REGISTRATION_END'), 2, 1, 1).setValues([['2099-01-01T00:00:00+05:30']]); assert.equal(vm.runInContext('isOpen_(config_())', context), true);
const publicSettings = vm.runInContext('publicSettings_(config_())', context); assert.equal(publicSettings.REGISTRATION_ENABLED, 'TRUE'); assert.equal('SPREADSHEET_ID' in publicSettings, false); assert.equal('BPL_OWNED_SPREADSHEET_ID' in publicSettings, false);
vm.runInContext('setupBplRegistration()', context); assert.equal(settingsSheet.getRange(findSettingRow('REGISTRATION_END'), 2, 1, 1).getValues()[0][0], '2099-01-01T00:00:00+05:30');
console.log('Settings tests passed: defaults, preservation, backend window enforcement, and public-only response.');
