/** Standalone BPL Kids Apps Script endpoint. It never calls BidWar services. */
const TAB = { registrations: 'REGISTRATIONS', players: 'PLAYERS', mentors: 'MENTORS', payments: 'PAYMENTS', files: 'FILES', audit: 'AUDIT_LOG', settings: 'SETTINGS' };
const SCHEMA = {
  REGISTRATIONS: ['Registration ID','Team Code','Timestamp','Association Name','Association Branch','Association Email','Association Mobile','Association Logo URL','Association Logo Public ID','Category','Branding Opted','Registration Fee','Branding Fee','Total Amount','UTR / Transaction ID','Payment Screenshot URL','Payment Screenshot Public ID','Registration Status'],
  PLAYERS: ['Registration ID','Team Code','Player Number','Player Name','Class','DOB','Parent Mobile','Parent Email','Player Photo URL','Player Photo Public ID','Jersey Number','Jersey Size','Cricket Role','Role-specific Fields'],
  MENTORS: ['Registration ID','Team Code','Mentor Name','Mentor Mobile','Mentor Second Mobile','Mentor Email','Mentor Photo URL','Mentor Photo Public ID'],
  PAYMENTS: ['Registration ID','Team Code','UTR / Transaction ID','Payment Screenshot URL','Payment Screenshot Public ID','Branding Opted','Registration Fee','Branding Fee','Total Fee'],
  FILES: ['Registration ID','Team Code','File Type','Cloudinary URL','Cloudinary Public ID','Cloudinary Folder','Timestamp'],
  AUDIT_LOG: ['Timestamp','Registration ID','Team Code','Event','Details'],
  SETTINGS: ['Setting','Value']
};
const DEFAULTS = {
  // Initial window placeholders only; confirm REGISTRATION_START/REGISTRATION_END in SETTINGS before enabling registration.
  REGISTRATION_ENABLED: 'false', REGISTRATION_START: '2026-01-01T00:00:00+05:30', REGISTRATION_END: '2026-10-01T23:59:00+05:30',
  TOURNAMENT_SLUG: 'bpl-kids-2026', REGISTRATION_PREFIX: 'BPL-', PLAYERS_PER_TEAM: '8', MENTORS_PER_TEAM: '1',
  CATEGORY_CLASSES_JSON: '{"Category 1":["4","5","6"],"Category 2":["7","8","9"]}', REGISTRATION_FEE: '8000', BRANDING_FEE: '5000', CLOUDINARY_FOLDER: 'bpl-kids-2026',
  ROLE_REQUIRED_FIELDS_JSON: '{"Batsman":["battingStyle"],"Bowler":["bowlingStyle"],"All Rounder":["battingStyle","bowlingStyle"],"Wicket Keeper":["battingStyle"]}',
  TOURNAMENT_NAME: 'BidWar Premier League — Kids Version', TOURNAMENT_DATES: '3rd & 4th October', TOURNAMENT_ORGANISER: 'Bidwar.in & KV TechMedia',
  TOURNAMENT_INFORMATION: 'Tournament details will be shared with registered teams.', TOURNAMENT_INCLUSIONS: 'Tournament inclusions will be shared with registered teams.',
  IMPORTANT_INSTRUCTIONS: 'Keep your Team Code ready for all tournament communication.', WHATSAPP_LINK: '', PAYMENT_LINK: '', PAYMENT_QR: '', PAYMENT_INSTRUCTIONS: 'Make the exact total payment using the payment link or QR code.', SPONSORS_JSON: '[]', ADMIN_EMAILS: '', MAX_PAYLOAD_BYTES: '60000'
};

/** Run once from the Apps Script editor. Safe to run again. */
function setupBplRegistration() {
  const lock = LockService.getScriptLock(); lock.waitLock(30000);
  try {
    const spreadsheet = getOrCreateSpreadsheet_();
    ensureSchema_(spreadsheet);
    ensureSettings_(spreadsheet);
    const result = { success: true, spreadsheetId: spreadsheet.getId(), spreadsheetUrl: spreadsheet.getUrl(), tabs: Object.values(TAB) };
    console.log(JSON.stringify(result));
    return result;
  } finally { lock.releaseLock(); }
}
function settingDefault_(key) { return PropertiesService.getScriptProperties().getProperty(key) || DEFAULTS[key] || ''; }
function getOrCreateSpreadsheet_() {
  const p = PropertiesService.getScriptProperties(), id = p.getProperty('SPREADSHEET_ID'), owned = p.getProperty('BPL_OWNED_SPREADSHEET_ID');
  if (id || owned) { if (!id || id !== owned) throw new Error('Refusing to use a spreadsheet not created by this BPL Apps Script. Clear both BPL spreadsheet properties only if you intentionally want a new dedicated sheet.'); return SpreadsheetApp.openById(id); }
  const spreadsheet = SpreadsheetApp.create('BPL Kids Registration 2026');
  p.setProperties({ SPREADSHEET_ID: spreadsheet.getId(), BPL_OWNED_SPREADSHEET_ID: spreadsheet.getId(), BPL_DEFAULT_SHEET_TO_REMOVE: spreadsheet.getSheets()[0].getSheetName() }, false);
  return spreadsheet;
}
function getSpreadsheet_() { const p = PropertiesService.getScriptProperties(); if (!p.getProperty('SPREADSHEET_ID')) return setupBplRegistration_(); const spreadsheet = getOrCreateSpreadsheet_(); ensureSchema_(spreadsheet); return spreadsheet; }
function setupBplRegistration_() { const lock = LockService.getScriptLock(); lock.waitLock(30000); try { const spreadsheet = getOrCreateSpreadsheet_(); ensureSchema_(spreadsheet); ensureSettings_(spreadsheet); return spreadsheet; } finally { lock.releaseLock(); } }
function ensureSchema_(spreadsheet) {
  Object.keys(SCHEMA).forEach(name => ensureSheet_(spreadsheet, name));
  const p = PropertiesService.getScriptProperties(), defaultName = p.getProperty('BPL_DEFAULT_SHEET_TO_REMOVE'), defaultSheet = defaultName && spreadsheet.getSheetByName(defaultName);
  if (defaultSheet && spreadsheet.getSheets().length > 1 && defaultSheet.getLastRow() === 0) { spreadsheet.deleteSheet(defaultSheet); p.deleteProperty('BPL_DEFAULT_SHEET_TO_REMOVE'); }
}
function ensureSheet_(spreadsheet, name) {
  let sheet = spreadsheet.getSheetByName(name); if (!sheet) sheet = spreadsheet.insertSheet(name);
  const required = SCHEMA[name], width = Math.max(sheet.getLastColumn(), required.length), existing = sheet.getLastRow() ? sheet.getRange(1, 1, 1, width).getValues()[0].map(String) : [];
  if (!existing.some(value => value.trim())) { sheet.getRange(1, 1, 1, required.length).setValues([required]); sheet.setFrozenRows(1); return sheet; }
  const missing = required.filter(header => !existing.includes(header)); if (missing.length) sheet.getRange(1, existing.length + 1, 1, missing.length).setValues([missing]); sheet.setFrozenRows(1); return sheet;
}
function ensureSettings_(spreadsheet) { const sheet = ensureSheet_(spreadsheet, TAB.settings), existing = getBplSettings_(spreadsheet), missing = Object.keys(DEFAULTS).filter(key => existing[key] === undefined); if (missing.length) sheet.getRange(sheet.getLastRow() + 1, 1, missing.length, 2).setValues(missing.map(key => [key, settingDefault_(key)])); return { ...Object.fromEntries(Object.keys(DEFAULTS).map(key => [key, settingDefault_(key)])), ...existing }; }
function getBplSettings_(spreadsheet) { const sheet = ensureSheet_(spreadsheet, TAB.settings), rows = sheet.getLastRow() > 1 ? sheet.getRange(2, 1, sheet.getLastRow() - 1, 2).getValues() : [], settings = {}; rows.forEach(([key, value]) => { const normalized = String(key || '').trim(); if (normalized && settings[normalized] === undefined) settings[normalized] = String(value); }); return settings; }
function config_() { const spreadsheet = getSpreadsheet_(), settings = ensureSettings_(spreadsheet), get = key => settings[key] === undefined ? settingDefault_(key) : settings[key]; return { spreadsheet, settings, enabled: String(get('REGISTRATION_ENABLED')).toLowerCase() === 'true', start: new Date(get('REGISTRATION_START')), end: new Date(get('REGISTRATION_END')), slug: get('TOURNAMENT_SLUG'), prefix: get('REGISTRATION_PREFIX'), playersPerTeam: Number(get('PLAYERS_PER_TEAM')), categoryClasses: JSON.parse(get('CATEGORY_CLASSES_JSON')), registrationFee: Number(get('REGISTRATION_FEE')), brandingFee: Number(get('BRANDING_FEE')), roleRequiredFields: JSON.parse(get('ROLE_REQUIRED_FIELDS_JSON')), cloudinaryFolder: get('CLOUDINARY_FOLDER'), adminEmails: get('ADMIN_EMAILS').split(',').map(x => x.trim()).filter(Boolean), tournamentName: get('TOURNAMENT_NAME'), dates: get('TOURNAMENT_DATES'), information: get('TOURNAMENT_INFORMATION'), inclusions: get('TOURNAMENT_INCLUSIONS'), instructions: get('IMPORTANT_INSTRUCTIONS'), whatsapp: get('WHATSAPP_LINK'), maxPayload: Number(get('MAX_PAYLOAD_BYTES')) }; }
const PUBLIC_SETTING_KEYS = ['REGISTRATION_ENABLED','REGISTRATION_START','REGISTRATION_END','TOURNAMENT_NAME','TOURNAMENT_DATES','TOURNAMENT_ORGANISER','PAYMENT_LINK','PAYMENT_QR','PAYMENT_INSTRUCTIONS','WHATSAPP_LINK'];
function publicSettings_(c) { const settings = {}; PUBLIC_SETTING_KEYS.forEach(key => settings[key] = c.settings[key] === undefined ? settingDefault_(key) : c.settings[key]); return settings; }
function doGet(e) { const c = config_(); if (e && e.parameter && e.parameter.action === 'getSettings') return output_({ success: true, settings: publicSettings_(c), open: isOpen_(c) }); return output_({ success: true, service: 'BPL Kids standalone registration endpoint', open: isOpen_(c) }); }
function doPost(e) { try { const raw = e && e.postData && e.postData.contents, c = config_(); if (!raw || raw.length > c.maxPayload) throw new Error('Malformed or oversized request.'); return output_({ success: true, ...register_(JSON.parse(raw), c) }); } catch (error) { return output_({ success: false, error: error.message || 'Unable to process registration.' }); } }
function output_(value) { return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON); }
function isOpen_(c) { const now = new Date(); return c.enabled && now >= c.start && now <= c.end; }
function register_(p, c) { if (!isOpen_(c)) throw new Error('Registration is closed.'); validate_(p, c); const cache = CacheService.getScriptCache(), key = 'idempotency:' + p.idempotencyKey, cached = cache.get(key); if (cached) return JSON.parse(cached); const lock = LockService.getScriptLock(); lock.waitLock(25000); try { const again = cache.get(key); if (again) return JSON.parse(again); const result = writeRegistration_(p, c); cache.put(key, JSON.stringify(result), 21600); try { sendConfirmation_(p, result, c); } catch (error) { appendRow_(TAB.audit, { Timestamp: new Date(), 'Registration ID': result.registrationId, 'Team Code': result.teamCode, Event: 'EMAIL_FAILED', Details: String(error) }, c); } return result; } finally { lock.releaseLock(); } }
function validate_(p, c) { const mobile = /^[6-9]\d{9}$/, mail = /^[^\s@]+@[^\s@]+\.[^\s@]+$/; if (!p || p.tournamentSlug !== c.slug || !p.idempotencyKey) throw new Error('Invalid tournament request.'); if (!p.association || !p.association.name || !p.association.branch || !mail.test(p.association.email) || !mobile.test(p.association.mobile) || !file_(p.association.logo,c)) throw new Error('Invalid association details.'); const classes = c.categoryClasses[p.category]; if (!classes || !Array.isArray(p.players) || p.players.length !== c.playersPerTeam) throw new Error(`Exactly ${c.playersPerTeam} valid players are required.`); p.players.forEach((x,i) => { const required = c.roleRequiredFields[x.role]; if (!x.name || !classes.includes(x.className) || !x.dob || !mobile.test(x.parentMobile) || !mail.test(x.parentEmail) || !file_(x.photo,c) || !/^[1-9]\d?$/.test(String(x.jerseyNumber)) || !x.jerseySize || !required || required.some(key => !x.roleDetails || !x.roleDetails[key])) throw new Error('Invalid player details for Player '+(i+1)+'.'); }); if (!p.mentor || !p.mentor.name || !mobile.test(p.mentor.mobile) || (p.mentor.secondMobile && !mobile.test(p.mentor.secondMobile)) || !mail.test(p.mentor.email) || !file_(p.mentor.photo,c)) throw new Error('Invalid mentor details.'); if (!p.payment || typeof p.payment.brandingOpted !== 'boolean' || !String(p.payment.utr || '').trim() || !file_(p.payment.screenshot,c) || p.payment.registrationFee !== c.registrationFee || p.payment.brandingFee !== (p.payment.brandingOpted ? c.brandingFee : 0) || p.payment.totalAmount !== p.payment.registrationFee + p.payment.brandingFee) throw new Error('Invalid payment details.'); }
function file_(f,c) { return f && /^https:\/\/res\.cloudinary\.com\//.test(f.secureUrl || '') && String(f.publicId || '').startsWith(c.cloudinaryFolder+'/'); }
function appendRow_(name, values, c) { const sheet = ensureSheet_(c.spreadsheet, name), headers = sheet.getRange(1,1,1,sheet.getLastColumn()).getValues()[0].map(String), row = headers.map(header => values[header] === undefined ? '' : values[header]); sheet.getRange(sheet.getLastRow()+1, 1, 1, headers.length).setValues([row]); }
function writeRegistration_(p,c) { const registrations = ensureSheet_(c.spreadsheet,TAB.registrations), teamCodes = registrations.getLastRow() > 1 ? registrations.getRange(2,2,registrations.getLastRow()-1,1).getValues().flat().map(String) : [], registrationId = c.prefix + String(registrations.getLastRow()).padStart(4,'0'), teamCode = uniqueCode_(teamCodes), at = new Date(), base = { 'Registration ID': registrationId, 'Team Code': teamCode }; appendRow_(TAB.registrations, { ...base, Timestamp:at, 'Association Name':p.association.name, 'Association Branch':p.association.branch, 'Association Email':p.association.email, 'Association Mobile':p.association.mobile, 'Association Logo URL':p.association.logo.secureUrl, 'Association Logo Public ID':p.association.logo.publicId, Category:p.category, 'Branding Opted':p.payment.brandingOpted?'YES':'NO', 'Registration Fee':p.payment.registrationFee, 'Branding Fee':p.payment.brandingFee, 'Total Amount':p.payment.totalAmount, 'UTR / Transaction ID':p.payment.utr, 'Payment Screenshot URL':p.payment.screenshot.secureUrl, 'Payment Screenshot Public ID':p.payment.screenshot.publicId, 'Registration Status':'SUBMITTED' }, c); p.players.forEach(x => appendRow_(TAB.players, { ...base, 'Player Number':x.number, 'Player Name':x.name, Class:x.className, DOB:x.dob, 'Parent Mobile':x.parentMobile, 'Parent Email':x.parentEmail, 'Player Photo URL':x.photo.secureUrl, 'Player Photo Public ID':x.photo.publicId, 'Jersey Number':x.jerseyNumber, 'Jersey Size':x.jerseySize, 'Cricket Role':x.role, 'Role-specific Fields':JSON.stringify(x.roleDetails) }, c)); appendRow_(TAB.mentors, { ...base, 'Mentor Name':p.mentor.name, 'Mentor Mobile':p.mentor.mobile, 'Mentor Second Mobile':p.mentor.secondMobile, 'Mentor Email':p.mentor.email, 'Mentor Photo URL':p.mentor.photo.secureUrl, 'Mentor Photo Public ID':p.mentor.photo.publicId }, c); appendRow_(TAB.payments, { ...base, 'UTR / Transaction ID':p.payment.utr, 'Payment Screenshot URL':p.payment.screenshot.secureUrl, 'Payment Screenshot Public ID':p.payment.screenshot.publicId, 'Branding Opted':p.payment.brandingOpted?'YES':'NO', 'Registration Fee':p.payment.registrationFee, 'Branding Fee':p.payment.brandingFee, 'Total Fee':p.payment.totalAmount }, c); [['Association Logo',p.association.logo],...p.players.map(x=>['Player '+x.number+' Photo',x.photo]),['Mentor Photo',p.mentor.photo],['Payment Screenshot',p.payment.screenshot]].forEach(x => appendRow_(TAB.files, { ...base, 'File Type':x[0], 'Cloudinary URL':x[1].secureUrl, 'Cloudinary Public ID':x[1].publicId, 'Cloudinary Folder':c.cloudinaryFolder, Timestamp:at }, c)); appendRow_(TAB.audit, { Timestamp:at, ...base, Event:'REGISTERED', Details:'Registration submitted' }, c); return { registrationId, teamCode }; }
function uniqueCode_(used) { const set=new Set(used); for(let tries=0;tries<100;tries++){const code=String(Math.floor(1000+Math.random()*9000));if(!set.has(code))return code;} throw new Error('Could not allocate a team code. Please retry.'); }
function sendConfirmation_(p,result,c) { const recipients=[...new Set([p.association.email,p.mentor.email,...p.players.map(x=>x.parentEmail),...c.adminEmails].filter(Boolean))].join(','), rows=p.players.map(x=>`<tr><td>${x.number}</td><td>${escape_(x.name)}</td><td>${x.className}</td><td>${escape_(x.role)}</td></tr>`).join(''), html=`<h2>Registration Successful</h2><p><b>${escape_(c.tournamentName)}</b></p><p><b>Registration ID:</b> ${result.registrationId}<br><b>Team Code:</b> ${result.teamCode}<br><b>Association:</b> ${escape_(p.association.name)} — ${escape_(p.category)}<br><b>Tournament dates:</b> ${escape_(c.dates)}</p><h3>Payment</h3><p>Registration Fee: ₹${p.payment.registrationFee}<br>Branding: ${p.payment.brandingOpted?'Yes':'No'} (₹${p.payment.brandingFee})<br><b>Total Amount: ₹${p.payment.totalAmount}</b><br>UTR: ${escape_(p.payment.utr)}</p><h3>Players</h3><table border="1" cellpadding="6"><tr><th>#</th><th>Name</th><th>Class</th><th>Role</th></tr>${rows}</table><p><b>Mentor:</b> ${escape_(p.mentor.name)}</p><p><b>Tournament information:</b> ${escape_(c.information)}<br><b>Inclusions:</b> ${escape_(c.inclusions)}<br><b>Important instructions:</b> ${escape_(c.instructions)}</p><p><a href="${escape_(c.whatsapp)}">Join the WhatsApp Community</a></p>`; MailApp.sendEmail({to:recipients,subject:`${c.tournamentName}: Team ${result.teamCode} registration confirmed`,htmlBody:html,body:`Registration Successful. Registration ID: ${result.registrationId}. Team Code: ${result.teamCode}.`}); }
function escape_(value) { return String(value||'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x])); }
