// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/led-display/CurrentEnhanced.tsx": () => import("../components/mockups/led-display/CurrentEnhanced.tsx"),
  "./components/mockups/led-display/NeonMumbai.tsx": () => import("../components/mockups/led-display/NeonMumbai.tsx"),
  "./components/mockups/led-display/StadiumCard.tsx": () => import("../components/mockups/led-display/StadiumCard.tsx")
};
