// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/led-display/BroadcastGold.tsx": () => import("../components/mockups/led-display/BroadcastGold.tsx"),
  "./components/mockups/led-display/CurrentEnhanced.tsx": () => import("../components/mockups/led-display/CurrentEnhanced.tsx"),
  "./components/mockups/led-display/FestivalNight.tsx": () => import("../components/mockups/led-display/FestivalNight.tsx"),
  "./components/mockups/led-display/IceBlue.tsx": () => import("../components/mockups/led-display/IceBlue.tsx"),
  "./components/mockups/led-display/NeonMumbai.tsx": () => import("../components/mockups/led-display/NeonMumbai.tsx"),
  "./components/mockups/led-display/StadiumCard.tsx": () => import("../components/mockups/led-display/StadiumCard.tsx"),
  "./components/mockups/led-display/Top5AuctionBroadcast.tsx": () => import("../components/mockups/led-display/Top5AuctionBroadcast.tsx"),
  "./components/mockups/operator-panel/BeginnerFriendly.tsx": () => import("../components/mockups/operator-panel/BeginnerFriendly.tsx"),
  "./components/mockups/operator-panel/BroadcastPremium.tsx": () => import("../components/mockups/operator-panel/BroadcastPremium.tsx"),
  "./components/mockups/operator-panel/ProOperator.tsx": () => import("../components/mockups/operator-panel/ProOperator.tsx")
};
