import type { ResourceKindCatalogEntry } from "../types.ts";

/**
 * Resource Kind catalog — facility types Scheduling may reference (EPIC-07).
 * Scheduling never owns Resources; bridges map sport tables → instances.
 */
export const RESOURCE_KIND_CATALOG: readonly ResourceKindCatalogEntry[] = [
  {
    kind: "resource_kind",
    id: "court",
    version: "1.0.0",
    displayName: "Court",
    description: "Indoor/outdoor court resource.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "recommended",
  },
  {
    kind: "resource_kind",
    id: "ground",
    version: "1.0.0",
    displayName: "Ground",
    description: "Cricket / outdoor ground or venue-equivalent.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "recommended",
  },
  {
    kind: "resource_kind",
    id: "arena",
    version: "1.0.0",
    displayName: "Arena",
    description: "Arena facility.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "advanced",
  },
  {
    kind: "resource_kind",
    id: "mat",
    version: "1.0.0",
    displayName: "Mat",
    description: "Mat surface resource.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "advanced",
  },
  {
    kind: "resource_kind",
    id: "table",
    version: "1.0.0",
    displayName: "Table",
    description: "Table resource (e.g. table tennis).",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "advanced",
  },
  {
    kind: "resource_kind",
    id: "lane",
    version: "1.0.0",
    displayName: "Lane",
    description: "Lane resource.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "advanced",
  },
  {
    kind: "resource_kind",
    id: "track",
    version: "1.0.0",
    displayName: "Track",
    description: "Track resource.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "advanced",
  },
  {
    kind: "resource_kind",
    id: "virtual",
    version: "1.0.0",
    displayName: "Virtual",
    description: "Virtual / online resource.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "active",
    recommendation: "advanced",
  },
  {
    kind: "resource_kind",
    id: "future",
    version: "1.0.0",
    displayName: "Future",
    description: "Reserved for future resource kinds.",
    supportedCompetitionTypes: ["*"],
    supportedVariants: ["*"],
    status: "beta",
    recommendation: "advanced",
  },
];
