import type { VariantCatalogEntry } from "../types.ts";

export const CRICKET_VARIANTS: readonly VariantCatalogEntry[] = [
  {
    kind: "variant",
    id: "cricket.outdoor",
    version: "1.0.0",
    sportId: "cricket",
    displayName: "Outdoor Cricket",
    description: "Standard outdoor cricket formats (T20 / custom overs).",
    supportedCompetitionTypes: ["auction", "registered_teams", "hybrid", "practice"],
    supportedVariants: ["cricket.outdoor"],
    status: "active",
    recommendation: "recommended",
  },
  {
    kind: "variant",
    id: "cricket.box",
    version: "1.0.0",
    sportId: "cricket",
    displayName: "Box Cricket",
    description: "Indoor/box cricket with shorter overs and variant dismissals.",
    supportedCompetitionTypes: ["auction", "registered_teams", "hybrid", "practice"],
    supportedVariants: ["cricket.box"],
    status: "active",
    recommendation: "recommended",
  },
  {
    kind: "variant",
    id: "cricket.tennis_ball",
    version: "1.0.0",
    sportId: "cricket",
    displayName: "Tennis Ball",
    description: "Community tennis-ball cricket leagues.",
    supportedCompetitionTypes: ["auction", "registered_teams", "hybrid", "practice"],
    supportedVariants: ["cricket.tennis_ball"],
    status: "active",
    recommendation: "auto_suggested",
  },
  {
    kind: "variant",
    id: "cricket.indoor",
    version: "1.0.0",
    sportId: "cricket",
    displayName: "Indoor Cricket",
    description: "Indoor court cricket with compact presentation.",
    supportedCompetitionTypes: ["auction", "registered_teams", "hybrid", "practice"],
    supportedVariants: ["cricket.indoor"],
    status: "active",
    recommendation: "advanced",
  },
  {
    kind: "variant",
    id: "cricket.custom",
    version: "1.0.0",
    sportId: "cricket",
    displayName: "Custom",
    description: "Organizer-defined cricket variant — pick a custom rule pack.",
    supportedCompetitionTypes: ["auction", "registered_teams", "hybrid", "practice"],
    supportedVariants: ["cricket.custom"],
    status: "beta",
    recommendation: "advanced",
  },
];
