export const PRESENTATION_ENGINE_VERSION = "1.0.0";
export const PRESENTATION_ENGINE_INPUT_VERSION = "1.0.0";
export const PRESENTATION_SCHEMA_VERSION = "1.0.0";
export const PRESENTATION_CONTRACT_VERSION = "1.0.0";
export const PRESENTATION_COMPILER_VERSION = "1.0.0";
export const DETERMINISTIC_RESOLVED_AT = "1970-01-01T00:00:00.000Z";
