import type { RuleCategoryEntry } from "../types.ts";

export const RULE_CATEGORY_CATALOG: readonly RuleCategoryEntry[] = [
  {
    id: "match",
    version: "1.0.0",
    displayName: "Match Rules",
    description: "Innings length, squad size, and match structure policy.",
    status: "active",
    sortOrder: 10,
  },
  {
    id: "batting",
    version: "1.0.0",
    displayName: "Batting Rules",
    description: "Retire thresholds, re-entry, and batting policy.",
    status: "active",
    sortOrder: 20,
  },
  {
    id: "bowling",
    version: "1.0.0",
    displayName: "Bowling Rules",
    description: "Over limits, extras values, and free-hit policy.",
    status: "active",
    sortOrder: 30,
  },
  {
    id: "dismissal",
    version: "1.0.0",
    displayName: "Dismissal Rules",
    description: "Enabled dismissals and LBW policy (documentation structure only).",
    status: "active",
    sortOrder: 40,
  },
  {
    id: "boundary",
    version: "1.0.0",
    displayName: "Boundary Rules",
    description: "Four / six values and boundary customs.",
    status: "active",
    sortOrder: 50,
  },
  {
    id: "ground",
    version: "1.0.0",
    displayName: "Ground Rules",
    description: "Venue and interruption policy flags.",
    status: "active",
    sortOrder: 60,
  },
  {
    id: "powerplay",
    version: "1.0.0",
    displayName: "Powerplay Rules",
    description: "Powerplay enablement and phase policy.",
    status: "active",
    sortOrder: 70,
  },
  {
    id: "tie_break",
    version: "1.0.0",
    displayName: "Tie Break Rules",
    description: "Super over and tie resolution policy.",
    status: "active",
    sortOrder: 80,
  },
  {
    id: "penalty",
    version: "1.0.0",
    displayName: "Penalty Rules",
    description: "Penalty run awards and magnitudes.",
    status: "active",
    sortOrder: 90,
  },
  {
    id: "tournament",
    version: "1.0.0",
    displayName: "Tournament Rules",
    description: "Tournament-level format and structure policy.",
    status: "active",
    sortOrder: 100,
  },
  {
    id: "statistics",
    version: "1.0.0",
    displayName: "Statistics Rules",
    description: "Stats eligibility and aggregation policy flags.",
    status: "active",
    sortOrder: 110,
  },
  {
    id: "validation",
    version: "1.0.0",
    displayName: "Validation Rules",
    description: "Start-match and legality validation policy flags.",
    status: "active",
    sortOrder: 120,
  },
];
