/**
 * BidWar Master Workbook (BMW) — hidden manifest sheet.
 * Never editable. Validated before any import processing.
 */

import { createHash, randomUUID } from "node:crypto";

/** Canonical hidden sheet — stable forever */
export const BMW_MANIFEST_SHEET = "_BIDWAR_MANIFEST";

/** @deprecated Use BMW_MANIFEST_SHEET */
export const TMW_MANIFEST_SHEET = BMW_MANIFEST_SHEET;

/** Workbook format version (increment on breaking sheet/field changes) */
export const BMW_VERSION = "2.0.0";

/** Specification document version */
export const BMW_SPEC_VERSION = "2.0.0";

/** Minimum compatibility version accepted by this import engine */
export const BMW_COMPATIBILITY_VERSION = "1.0.0";

/** Import engine semver — bump when engine logic changes */
export const BMW_IMPORT_ENGINE_VERSION = "2.0.0";

/** Generator (export) semver */
export const BMW_GENERATOR_VERSION = "2.0.0";

/** Template version for blank workbooks */
export const BMW_TEMPLATE_VERSION = "2.0.0";

/** @deprecated Use BMW_VERSION */
export const TMW_VERSION = BMW_VERSION;

export const BMW_SUPPORTED_SPORTS = [
  "cricket",
  "badminton",
  "football",
  "volleyball",
  "kabaddi",
  "tennis",
  "table_tennis",
  "basketball",
  "hockey",
  "generic",
] as const;

export type BmwSupportedSport = (typeof BMW_SUPPORTED_SPORTS)[number];

export interface BmwManifest {
  workbookVersion: string;
  specificationVersion: string;
  generatedBy: string;
  generatedAt: string;
  supportedSports: string;
  generatorVersion: string;
  checksum: string;
  workbookUuid: string;
  templateVersion: string;
  compatibilityVersion: string;
  importEngineVersion: string;
}

export const BMW_MANIFEST_FIELDS: ReadonlyArray<{ key: keyof BmwManifest; label: string }> = [
  { key: "workbookVersion", label: "Workbook Version" },
  { key: "specificationVersion", label: "Specification Version" },
  { key: "generatedBy", label: "Generated By" },
  { key: "generatedAt", label: "Generated At" },
  { key: "supportedSports", label: "Supported Sports" },
  { key: "generatorVersion", label: "Generator Version" },
  { key: "checksum", label: "Checksum" },
  { key: "workbookUuid", label: "Workbook UUID" },
  { key: "templateVersion", label: "Template Version" },
  { key: "compatibilityVersion", label: "Compatibility Version" },
  { key: "importEngineVersion", label: "Import Engine Version" },
];

const LABEL_TO_KEY = new Map(BMW_MANIFEST_FIELDS.map((f) => [f.label.toLowerCase(), f.key]));

export function generateWorkbookUuid(): string {
  return randomUUID();
}

export function computeWorkbookChecksum(payload: string): string {
  return createHash("sha256").update(payload).digest("hex").slice(0, 16);
}

export function buildManifestPayload(manifest: Omit<BmwManifest, "checksum">): string {
  return JSON.stringify({
    workbookVersion: manifest.workbookVersion,
    specificationVersion: manifest.specificationVersion,
    generatedAt: manifest.generatedAt,
    workbookUuid: manifest.workbookUuid,
    templateVersion: manifest.templateVersion,
    compatibilityVersion: manifest.compatibilityVersion,
  });
}

export function createExportManifest(opts?: {
  sport?: string;
  workbookUuid?: string;
}): BmwManifest {
  const generatedAt = new Date().toISOString();
  const workbookUuid = opts?.workbookUuid ?? generateWorkbookUuid();
  const sports = opts?.sport ?? "cricket,badminton,football,volleyball,kabaddi,tennis,table_tennis";

  const base: Omit<BmwManifest, "checksum"> = {
    workbookVersion: BMW_VERSION,
    specificationVersion: BMW_SPEC_VERSION,
    generatedBy: "BidWar Master Workbook Generator",
    generatedAt,
    supportedSports: sports,
    generatorVersion: BMW_GENERATOR_VERSION,
    workbookUuid,
    templateVersion: BMW_TEMPLATE_VERSION,
    compatibilityVersion: BMW_COMPATIBILITY_VERSION,
    importEngineVersion: BMW_IMPORT_ENGINE_VERSION,
  };

  return {
    ...base,
    checksum: computeWorkbookChecksum(buildManifestPayload(base)),
  };
}

/** Parse manifest from key-value rows (Field | Value columns) */
export function parseManifestFromRows(rows: Record<string, unknown>[]): BmwManifest | null {
  if (rows.length === 0) return null;

  const values: Partial<BmwManifest> = {};
  for (const row of rows) {
    const fieldKey = String(row["Field"] ?? row["Key"] ?? row["Property"] ?? "").trim().toLowerCase();
    const value = String(row["Value"] ?? row["value"] ?? "").trim();
    if (!fieldKey || !value) continue;
    const manifestKey = LABEL_TO_KEY.get(fieldKey);
    if (manifestKey) values[manifestKey] = value;
  }

  if (!values.workbookVersion) return null;
  return values as BmwManifest;
}

export type ManifestValidationResult = {
  valid: boolean;
  manifest: BmwManifest | null;
  errors: string[];
  warnings: string[];
  isLegacy: boolean;
};

function parseSemver(v: string): [number, number, number] {
  const parts = v.replace(/^v/i, "").split(".").map((n) => parseInt(n, 10) || 0);
  return [parts[0] ?? 0, parts[1] ?? 0, parts[2] ?? 0];
}

function isCompatibleVersion(workbookVersion: string): boolean {
  const [wMaj] = parseSemver(workbookVersion);
  const [cMaj] = parseSemver(BMW_COMPATIBILITY_VERSION);
  return wMaj >= cMaj;
}

export function validateManifest(
  manifest: BmwManifest | null,
  opts?: { verifyChecksum?: boolean; contentPayload?: string },
): ManifestValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!manifest) {
    return {
      valid: false,
      manifest: null,
      errors: ["Missing _BIDWAR_MANIFEST sheet — workbook may be corrupt or from an unsupported source"],
      warnings: [],
      isLegacy: true,
    };
  }

  if (!manifest.workbookVersion) {
    errors.push("Manifest missing Workbook Version");
  } else if (!isCompatibleVersion(manifest.workbookVersion)) {
    errors.push(
      `Workbook version ${manifest.workbookVersion} is not supported (minimum ${BMW_COMPATIBILITY_VERSION})`,
    );
  }

  if (!manifest.workbookUuid) {
    warnings.push("Manifest missing Workbook UUID — import will proceed with a generated UUID");
  }

  if (opts?.verifyChecksum && manifest.checksum && opts.contentPayload) {
    const expected = computeWorkbookChecksum(opts.contentPayload);
    if (manifest.checksum !== expected) {
      errors.push("Manifest checksum mismatch — workbook may have been modified outside BidWar");
    }
  }

  if (manifest.importEngineVersion) {
    const [mMin] = parseSemver(manifest.importEngineVersion);
    const [eMin] = parseSemver(BMW_IMPORT_ENGINE_VERSION);
    if (mMin > eMin) {
      warnings.push(
        `Workbook was generated with import engine ${manifest.importEngineVersion}; current engine is ${BMW_IMPORT_ENGINE_VERSION}`,
      );
    }
  }

  return {
    valid: errors.length === 0,
    manifest,
    errors,
    warnings,
    isLegacy: false,
  };
}

/** Legacy TMW 1.x workbooks without manifest — allow with warning */
export function validateManifestOrLegacy(
  manifest: BmwManifest | null,
  hasKnownSheets: boolean,
): ManifestValidationResult {
  if (manifest) return validateManifest(manifest);
  if (hasKnownSheets) {
    return {
      valid: true,
      manifest: null,
      errors: [],
      warnings: ["Legacy workbook without _BIDWAR_MANIFEST — upgrade by re-exporting from BidWar"],
      isLegacy: true,
    };
  }
  return validateManifest(null);
}
