import { pdef } from "../helpers.ts";
import type { PresentationDefinitionEntry } from "../../types.ts";

/** Platform-wide presentation definitions — sportId "*". */
export const PLATFORM_PRESENTATION_DEFINITIONS: readonly PresentationDefinitionEntry[] = [
  // Tokens
  pdef({
    id: "presentation.token.color.primary",
    kind: "token",
    name: "Primary color token",
    description: "Primary accent color token id (semantic reference, not a hex asset).",
    type: "string",
    defaultValue: "color.primary",
  }),
  pdef({
    id: "presentation.token.color.secondary",
    kind: "token",
    name: "Secondary color token",
    description: "Secondary color token reference.",
    type: "string",
    defaultValue: "color.secondary",
  }),
  pdef({
    id: "presentation.token.font.score",
    kind: "token",
    name: "Score font token",
    description: "Typography token for primary score digits.",
    type: "string",
    defaultValue: "font.score",
  }),
  pdef({
    id: "presentation.token.spacing.compact",
    kind: "token",
    name: "Compact spacing token",
    description: "Spacing scale token for dense layouts.",
    type: "string",
    defaultValue: "spacing.compact",
  }),
  pdef({
    id: "presentation.token.spacing.large",
    kind: "token",
    name: "Large spacing token",
    description: "Spacing scale token for open layouts.",
    type: "string",
    defaultValue: "spacing.large",
  }),
  pdef({
    id: "presentation.token.safe_area.bottom",
    kind: "token",
    name: "Bottom safe-area token",
    description: "Semantic bottom safe-area token.",
    type: "string",
    defaultValue: "safe_area.bottom",
  }),

  // Styles
  pdef({
    id: "presentation.style.score",
    kind: "style",
    name: "Score style",
    description: "Style binding primary score presentation tokens.",
    type: "string",
    defaultValue: "style.score",
    tokenIds: [
      "presentation.token.font.score",
      "presentation.token.color.primary",
      "presentation.token.spacing.compact",
    ],
  }),
  pdef({
    id: "presentation.style.sponsor",
    kind: "style",
    name: "Sponsor style",
    description: "Style for sponsor strip presentation.",
    type: "string",
    defaultValue: "style.sponsor",
    tokenIds: [
      "presentation.token.color.secondary",
      "presentation.token.spacing.large",
      "presentation.token.safe_area.bottom",
    ],
  }),

  // Features
  pdef({
    id: "presentation.feature.sponsor_strip",
    kind: "feature",
    name: "Sponsor strip feature",
    description: "Enables sponsor strip presentation.",
    type: "boolean",
    defaultValue: true,
  }),
  pdef({
    id: "presentation.feature.clock",
    kind: "feature",
    name: "Clock feature",
    description: "Enables clock slot occupancy.",
    type: "boolean",
    defaultValue: true,
  }),
  pdef({
    id: "presentation.feature.primary_score",
    kind: "feature",
    name: "Primary score feature",
    description: "Enables primary score slot.",
    type: "boolean",
    defaultValue: true,
  }),
  pdef({
    id: "presentation.feature.ticker",
    kind: "feature",
    name: "Ticker feature",
    description: "Enables ticker presentation.",
    type: "boolean",
    defaultValue: true,
  }),
  pdef({
    id: "presentation.feature.animation",
    kind: "feature",
    name: "Animation feature",
    description: "Optional animation capability gate.",
    type: "boolean",
    defaultValue: false,
  }),
  pdef({
    id: "presentation.feature.player_card",
    kind: "feature",
    name: "Player card feature",
    description: "Enables player card slot.",
    type: "boolean",
    defaultValue: true,
  }),

  // Regions (structural — defaultValue is region key)
  pdef({
    id: "presentation.region.header",
    kind: "region",
    name: "Header region",
    description: "Top semantic region.",
    type: "string",
    defaultValue: "Header",
    styleId: "presentation.style.score",
  }),
  pdef({
    id: "presentation.region.scoreboard",
    kind: "region",
    name: "Scoreboard region",
    description: "Primary scoreboard semantic region.",
    type: "string",
    defaultValue: "Scoreboard",
    styleId: "presentation.style.score",
    dependencies: ["presentation.region.header"],
  }),
  pdef({
    id: "presentation.region.bottom_safe_area",
    kind: "region",
    name: "Bottom safe area region",
    description: "Bottom safe-area semantic region.",
    type: "string",
    defaultValue: "BottomSafeArea",
    styleId: "presentation.style.sponsor",
  }),
  pdef({
    id: "presentation.region.sponsor_strip",
    kind: "region",
    name: "Sponsor strip region",
    description: "Sponsor strip semantic region.",
    type: "string",
    defaultValue: "SponsorStrip",
    styleId: "presentation.style.sponsor",
    dependencies: ["presentation.region.bottom_safe_area"],
  }),

  // Slots
  pdef({
    id: "presentation.slot.primary_score",
    kind: "slot",
    name: "Primary score slot",
    description: "Occupies scoreboard with primary score.",
    type: "string",
    defaultValue: "PrimaryScore",
    regionId: "presentation.region.scoreboard",
    featureId: "presentation.feature.primary_score",
  }),
  pdef({
    id: "presentation.slot.clock",
    kind: "slot",
    name: "Clock slot",
    description: "Occupies header with clock.",
    type: "string",
    defaultValue: "Clock",
    regionId: "presentation.region.header",
    featureId: "presentation.feature.clock",
  }),
  pdef({
    id: "presentation.slot.sponsor",
    kind: "slot",
    name: "Sponsor slot",
    description: "Occupies sponsor strip region.",
    type: "string",
    defaultValue: "Sponsor",
    regionId: "presentation.region.sponsor_strip",
    featureId: "presentation.feature.sponsor_strip",
  }),
  pdef({
    id: "presentation.slot.ticker",
    kind: "slot",
    name: "Ticker slot",
    description: "Occupies bottom band with ticker.",
    type: "string",
    defaultValue: "Ticker",
    regionId: "presentation.region.bottom_safe_area",
    featureId: "presentation.feature.ticker",
  }),
  pdef({
    id: "presentation.slot.player_card",
    kind: "slot",
    name: "Player card slot",
    description: "Occupies scoreboard adjacency with player card.",
    type: "string",
    defaultValue: "PlayerCard",
    regionId: "presentation.region.scoreboard",
    featureId: "presentation.feature.player_card",
  }),
];
