import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

export const tournamentsTable = sqliteTable("tournaments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  sport: text("sport").notNull().default("cricket"),
  venue: text("venue"),
  auctionDate: text("auction_date"),
  organizerName: text("organizer_name"),
  organizerMobile: text("organizer_mobile"),
  organizerEmail: text("organizer_email"),
  logoUrl: text("logo_url"),
  sponsorLogos: text("sponsor_logos"),
  basePurse: integer("base_purse").notNull().default(10000000),
  minBid: integer("min_bid").notNull().default(100000),
  bidIncrement: integer("bid_increment").notNull().default(100000),
  bidTier1UpTo: integer("bid_tier1_up_to").notNull().default(100000),
  bidTier1Increment: integer("bid_tier1_increment").notNull().default(25000),
  bidTier2UpTo: integer("bid_tier2_up_to").notNull().default(200000),
  bidTier2Increment: integer("bid_tier2_increment").notNull().default(50000),
  bidTier3Increment: integer("bid_tier3_increment").notNull().default(100000),
  bidTiers: text("bid_tiers"),
  timerSeconds: integer("timer_seconds").notNull().default(30),
  bidTimerSeconds: integer("bid_timer_seconds").notNull().default(15),
  playerSelectionMode: text("player_selection_mode").notNull().default("sequential"),
  status: text("status").notNull().default("setup"),
  cloudId: integer("cloud_id"),
  cloudBaseUrl: text("cloud_base_url"),
  exportToken: text("export_token"),
  localModeEnabled: integer("local_mode_enabled").notNull().default(0),
  operatorPin: text("operator_pin"),
  createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),
  updatedAt: text("updated_at").notNull().$defaultFn(() => new Date().toISOString()),
});

export type Tournament = typeof tournamentsTable.$inferSelect;
